In [2]:
import numpy as np
from keras.datasets import imdb
from keras.models import Sequential
from keras.layers import Dense

In [3]:
(train_x, train_y), (test_x, test_y)=imdb.load_data(num_words=10000)

In [5]:
train_y

array([1, 0, 0, ..., 0, 1, 0])

In [6]:
train_y=np.asarray(train_y).astype("float32")

In [7]:
train_y

array([1., 0., 0., ..., 0., 1., 0.], dtype=float32)

In [8]:
test_y=np.asarray(test_y).astype("float32")

In [13]:
def vectorize_sequences(sequences, dimension=10000):
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1.
        return results

x_train = vectorize_sequences(train_x)
x_test = vectorize_sequences(test_x)

In [14]:
x_train

array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [25]:

model = Sequential()
model.add(Dense(32, activation='tanh', input_shape=(10000,)))
model.add(Dense(100, activation='tanh'))
model.add(Dense(1, activation='sigmoid'))

In [26]:
model.compile(optimizer="rmsprop", loss="binary_crossentropy", metrics=["accuracy"])

In [27]:
model.fit(x_train, train_y, batch_size=128, epochs=8)

Epoch 1/8
25000/25000 [==============================] - 2s 96us/step - loss: 0.6934 - acc: 0.4959
Epoch 2/8
25000/25000 [==============================] - 2s 95us/step - loss: 0.6933 - acc: 0.4989
Epoch 3/8
25000/25000 [==============================] - 2s 93us/step - loss: 0.6932 - acc: 0.5030
Epoch 4/8
25000/25000 [==============================] - 2s 85us/step - loss: 0.6932 - acc: 0.4987
Epoch 5/8
25000/25000 [==============================] - 2s 85us/step - loss: 0.6932 - acc: 0.4984
Epoch 6/8
25000/25000 [==============================] - 2s 85us/step - loss: 0.6932 - acc: 0.4990
Epoch 7/8
25000/25000 [==============================] - 2s 85us/step - loss: 0.6932 - acc: 0.4986
Epoch 8/8
25000/25000 [==============================] - 2s 85us/step - loss: 0.6932 - acc: 0.4946
